# Generated by Django 3.2.5 on 2021-09-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeapp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.leacturare')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField(default='2017-06-01')),
                ('time', models.TimeField(default='09:00')),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture')),
            ],
            options={
                'ordering': ['cr_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.leacturare')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.lecture')),
            ],
        ),
    ]
